apiVersion: apps/v1
kind: Deployment
metadata:
  name: energy-scheduler
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: energy-scheduler
  template:
    metadata:
      labels:
        app: energy-scheduler
    spec:
      serviceAccountName: energy-scheduler
      containers:
        - name: energy-scheduler
          image: energy-scheduler:latest
          imagePullPolicy: Never
          command: ["/root/energy-scheduler", "--config=/etc/kubernetes/scheduler-config.yaml"]
          volumeMounts:
            - name: scheduler-config-volume
              mountPath: /etc/kubernetes
              readOnly: true
      volumes:
        - name: scheduler-config-volume
          configMap:
            name: energy-scheduler-config
      nodeSelector:
        node-role.kubernetes.io/control-plane: ""
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
