apiVersion: apps/v1
kind: Deployment
metadata:
  name: energy-scheduler
  labels:
    app: energy-scheduler
spec:
  replicas: 3
  selector:
    matchLabels:
      app: energy-scheduler
  template:
    metadata:
      labels:
        app: energy-scheduler
    spec:
      containers:
        - name: energy-scheduler
          image: energy-scheduler:latest
          imagePullPolicy: Never
          command: ["sudo ./energy-scheduler"]
          args:
            - "--config=/etc/kubernetes/scheduler-config.yaml"
            - "--kubeconfig=$HOME/.kube/config"
            - "--master=https://localhost:6443"
            - "-v=4"
          volumeMounts:
            - name: config-volume
              mountPath: /etc/kubernetes
      volumes:
        - name: config-volume
          configMap:
            name: scheduler-config
