apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: energy-scheduler-role
rules:
  - apiGroups: [""]
    resources: ["pods", "nodes", "persistentvolumeclaims", "persistentvolumes", "replicationcontrollers", "services", "configmaps"]
    verbs: ["get", "list", "watch", "update", "patch", "create", "delete"]
  - apiGroups: ["policy"]
    resources: ["poddisruptionbudgets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["csinodes", "csidrivers", "storageclasses", "csistoragecapacities"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["statefulsets", "replicasets", "deployments"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: [""]
    resources: ["nodes/proxy"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["endpoints", "events"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]