apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: energy-scheduler-binding
subjects:
  - kind: ServiceAccount
    name: energy-scheduler
    namespace: default
roleRef:
  kind: ClusterRole
  name: energy-scheduler-role
  apiGroup: rbac.authorization.k8s.io
