apiVersion: apps/v1
kind: Deployment
metadata:
  name: energy-scheduler
  labels:
    app: energy-scheduler
spec:
  replicas: 3
  selector:
    matchLabels:
      app: energy-scheduler
  template:
    metadata:
      labels:
        app: energy-scheduler
    spec:
      containers:
        - name: energy-scheduler
          image: lvhelt/energy-scheduler:v1.5
          imagePullPolicy: Always
          command: ["./energy-scheduler"]
          args:
            - "--config=/etc/kubernetes/scheduler-config.yaml"
            - "--authentication-kubeconfig=/etc/kubernetes/scheduler.conf"
            - "--authorization-kubeconfig=/etc/kubernetes/scheduler.conf"
            - "--master=https://localhost:6443"
            - "-v=9"
          env:
            - name: KUBECONFIG
              value: "/etc/kubernetes/scheduler.conf"
          volumeMounts:
            - name: config-volume
              mountPath: /etc/kubernetes
              readOnly: true
      volumes:
        - name: config-volume
          configMap:
            name: scheduler-config
