apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: energy-scheduler-role
rules:
  - apiGroups: [""]
    resources: ["pods", "nodes", "persistentvolumeclaims", "persistentvolumes", "replicationcontrollers", "services", "configmaps"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["policy"]
    resources: ["poddisruptionbudgets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["csinodes", "csidrivers", "storageclasses", "csistoragecapacities"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["statefulsets", "replicasets"]
    verbs: ["get", "list", "watch"]
