kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  apiServerAddress: "127.0.0.1"
  apiServerPort: 6443
nodes:
  - role: control-plane
    image: kindest/node:v1.27.3
    extraPortMappings:
      - containerPort: 30000
        hostPort: 30000
        protocol: TCP
      - containerPort: 80
        hostPort: 80
        protocol: TCP
      - containerPort: 443
        hostPort: 443
        protocol: TCP
  - role: worker
    image: kindest/node:v1.27.3
    extraMounts:
      - hostPath: /data
        containerPath: /mnt/data
  - role: worker
    image: kindest/node:v1.27.3
    extraMounts:
      - hostPath: /data
        containerPath: /mnt/data
  - role: worker
    image: kindest/node:v1.27.3
    extraMounts:
      - hostPath: /data
        containerPath: /mnt/data
