apiVersion: v1
kind: ServiceAccount
metadata:
  name: energy-scheduler
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: energy-scheduler-role
rules:
  - apiGroups: [""]
    resources: ["nodes", "pods", "pods/status", "pods/binding", "services", "namespaces", "persistentvolumes", "persistentvolumeclaims"]
    verbs: ["watch", "list", "get", "patch", "update", "create"]
  - apiGroups: ["scheduling.k8s.io"]
    resources: ["priorityclasses"]
    verbs: ["watch", "list", "get"]
  - apiGroups: ["events.k8s.io"]
    resources: ["events"]
    verbs: ["create", "patch"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["replicasets", "statefulsets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["policy"]
    resources: ["poddisruptionbudgets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["create", "get", "update"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["csistoragecapacities", "csinodes", "csidrivers", "storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["replicationcontrollers"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: energy-scheduler-rolebinding
subjects:
  - kind: ServiceAccount
    name: energy-scheduler
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: energy-scheduler-role
  apiGroup: rbac.authorization.k8s.io
