apiVersion: kubescheduler.config.k8s.io/v1
kind: KubeSchedulerConfiguration
profiles:
  - schedulerName: energy-aware-scheduler
    plugins:
      score:
        enabled:
          - name: EnergyEfficientScheduler
        disabled:
          - name: "*"
    pluginConfig:
      - name: EnergyEfficientScheduler
        args: {}
