apiVersion: kubescheduler.config.k8s.io/v1beta1
kind: KubeSchedulerConfiguration
profiles:
  - schedulerName: energy-efficient-scheduler
    plugins:
      score:
        enabled:
          - name: EnergyEfficientScheduler
