apiVersion: v1
kind: ConfigMap
metadata:
  name: scheduler-config
data:
  scheduler-config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1beta1
    kind: KubeSchedulerConfiguration
    profiles:
      - schedulerName: energy-scheduler
        plugins:
          score:
            enabled:
              - name: EnergyEfficientScheduler
            disabled:
              - name: "*"