apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  labels:
    app: test
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:
        cpu: "100m"  # Request 100 millicores of CPU
        memory: "128Mi"  # Request 128 MiB of memory
      limits:
        cpu: "200m"  # Limit to 200 millicores of CPU
        memory: "256Mi"  # Limit to 256 MiB of memory
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule
  restartPolicy: Always