apiVersion: v1
kind: Service
metadata:
  name: observability-service
  namespace: kube-system
spec:
  selector:
    app: observability-service
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001