apiVersion: v1
kind: Pod
metadata:
  name: memory-stress-{{.Replica}}
  namespace: kube-burner
  labels:
    app: app
spec:
  schedulerName: energy-scheduler
  containers:
    - name: stress-ng
      image: polinux/stress
      command: ["stress"]
      args: ["--vm", "1", "--vm-bytes", "360M", "--vm-hang", "0"]
      resources:
        requests:
          memory: "300Mi"
          cpu: "100m"
        limits:
          memory: "460Mi"
  restartPolicy: Never
