apiVersion: v1
kind: Service
metadata:
  name: kuberlbridge
  namespace: kube-system
spec:
  selector:
    app: kuberlbridge
  ports:
    - protocol: TCP
      port: 3000  # The port exposed by the service
      targetPort: 3000  # The port inside the container
