global:
  gc: true

jobs:
  - name: kube-burner-job
    namespace: kube-burner-job
    jobIterations: 10
    qps: 5
    burst: 5
    namespacedIterations: true
    cleanup: true
    jobPause: 1s
    objects:
      - objectTemplate: "C:/Users/jonat/OneDrive/Dokumenter/scheduler/kube-scheduler/Kubernetes-energy-aware-scheduler/kube-burner-test/deployment.yml"
        replicas: 1
