apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuberlbridge
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kuberlbridge
  template:
    metadata:
      labels:
        app: kuberlbridge
    spec:
      nodeSelector:
        node-role.kubernetes.io/control-plane: ""
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
      containers:
        - name: kuberlbridge
          image: lvhelt/kuberlbridge:v1.0
          ports:
            - containerPort: 3000
          imagePullPolicy: Always